from os import close
''' SO THERE ARE TWO MODES IN WHICH WE CAN WRITE IN PYTHON THE FIRST ONE BEING WRITE AND THE OTHER ONE IS APPEND WE USE WRITE WHILE WE ARE CEREATING THE FILE AND  WE WANT OVERRIDE THE DATA OF THE PREVIOUS FILE '''

#f=open('another.txt','w')     #IF WE USE THIS WHOLE TEXT WILL BE OVERWRITTEN
f=open('another.txt','a')     #IF WE USE THIS  TEXT WILL BE ADDED TO THE EXISTING TEXT
f.write("KYA HAL H BHAI KE ") #WE CAN CALL THIS MULTIPLE TIMES
f.write("KYA HAL H BHAI KE \n") 
f.write("KYA HAL H BHAI KE\n ") 
f.write("KYA HAL H BHAI KE ") 

f.close()